export const cities = [
  {
    value: "Nanggroe Aceh Darussalam",
    cities: [
      { value: "Kota Langsa", label: "Kota Langsa" },
      { value: "Kota Lhokseumawe", label: "Kota Lhokseumawe" },
      { value: "Kota Sabang", label: "Kota Sabang" },
      { value: "Kota Banda Aceh", label: "Kota Banda Aceh" },
      { value: "Kab. Bener Meriah", label: "Kab. Bener Meriah" },
      { value: "Kab. Aceh Tamiang", label: "Kab. Aceh Tamiang" },
      { value: "Kab. Nagan Jaya", label: "Kab. Nagan Jaya" },
      { value: "Kab. Aceh Jaya", label: "Kab. Aceh Jaya" },
      { value: "Kab. Gayo Lues", label: "Kab. Gayo Lues" },
      { value: "Kab. Aceh Barat Daya", label: "Kab. Aceh Barat Daya" },
      { value: "Kab. Bireun", label: "Kab. Bireun" },
      { value: "Kab. Aceh Singkil", label: "Kab. Aceh Singkil" },
      { value: "Kab. Simeulue", label: "Kab. Simeulue" },
      { value: "Kab. Aceh Utara", label: "Kab. Aceh Utara" },
      { value: "Kab. Pidie", label: "Kab. Pidie" },
      { value: "Kab. Aceh Besar", label: "Kab. Aceh Besar" },
      { value: "Kab. Aceh Barat", label: "Kab. Aceh Barat" },
      { value: "Kab. Tengah", label: "Kab. Tengah" },
      { value: "Kab. Aceh Timur", label: "Kab. Aceh Timur" },
      { value: "Kab. Aceh Tenggara", label: "Kab. Aceh Tenggara" },
      { value: "Kab. Aceh Selatan", label: "Kab. Aceh Selatan" },
    ],
  },
  {
    value: "Sumatera Utara",
    cities: [
      { value: "Kota Padang Sidempuan", label: "Kota Padang Sidempuan" },
      { value: "Kota Tebing Tinggi", label: "Kota Tebing Tinggi" },
      { value: "Kota Binjai", label: "Kota Binjai" },
      { value: "Kota Tanjung Balai", label: "Kota Tanjung Balai" },
      { value: "Kota Sibolga", label: "Kota Sibolga" },
      { value: "Kota Pematang Siantar", label: "Kota Pematang Siantar" },
      { value: "Kota Medan", label: "Kota Medan" },
      { value: "Kab. Serdang Bedagai ", label: "Kab. Serdang Bedagai " },
      { value: "Kab. Samosir ", label: "Kab. Samosir " },
      { value: "Kab. Humbang Hasundutan", label: "Kab. Humbang Hasundutan" },
      { value: "Kab. Pakpak Barat", label: "Kab. Pakpak Barat" },
      { value: "Kab. Nias Selatan", label: "Kab. Nias Selatan" },
      { value: "Kab. Mandailing Natal", label: "Kab. Mandailing Natal" },
      { value: "Kab. Toba Samosir", label: "Kab. Toba Samosir" },
      { value: "Kab. Dairi", label: "Kab. Dairi" },
      { value: "Kab. Labuhan Batu", label: "Kab. Labuhan Batu" },
      { value: "Kab. Asahan", label: "Kab. Asahan" },
      { value: "Kab. Simalungun", label: "Kab. Simalungun" },
      { value: "Kab. Deli Serdang", label: "Kab. Deli Serdang" },
      { value: "Kab. Karo", label: "Kab. Karo" },
      { value: "Kab. Langkat", label: "Kab. Langkat" },
      { value: "Kab. Nias", label: "Kab. Nias" },
      { value: "Kab. Tapanuli Selatan", label: "Kab. Tapanuli Selatan" },
      { value: "Kab. Tapanuli Utara", label: "Kab. Tapanuli Utara" },
      { value: "Kab. Tapanuli Tengah", label: "Kab. Tapanuli Tengah" },
    ],
  },
  {
    value: "Sumatera Barat",
    cities: [
      { value: "Kota Pariaman", label: "Kota Pariaman" },
      { value: "Kota Payakumbuh", label: "Kota Payakumbuh" },
      { value: "Kota Bukittinggi", label: "Kota Bukittinggi" },
      { value: "Kota Padang Panjang", label: "Kota Padang Panjang" },
      { value: "Kota Sawhlunto", label: "Kota Sawhlunto" },
      { value: "Kota Solok", label: "Kota Solok" },
      { value: "Kota Padang", label: "Kota Padang" },
      { value: "Kab. Pasaman Barat ", label: "Kab. Pasaman Barat " },
      { value: "Kab. Solok Selatan ", label: "Kab. Solok Selatan " },
      { value: "Kab. Dharmasraya", label: "Kab. Dharmasraya" },
      { value: "Kab. Kepulauan Mentawai", label: "Kab. Kepulauan Mentawai" },
      { value: "Kab. Pasaman ", label: "Kab. Pasaman " },
      { value: "Kab. Lima Puluh Kota", label: "Kab. Lima Puluh Kota" },
      { value: "Kab. Agam", label: "Kab. Agam" },
      { value: "Kab. Padang Pariaman", label: "Kab. Padang Pariaman" },
      { value: "Kab. Tanah Datar", label: "Kab. Tanah Datar" },
      { value: "Kab. Sw.lunto", label: "Kab. Sw.lunto" },
      { value: "Kab. Solok", label: "Kab. Solok" },
      { value: "Kab.pesisir Selatan", label: "Kab.pesisir Selatan" },
    ],
  },
  {
    value: "Riau",
    cities: [
      { value: "Kota Dumai", label: "Kota Dumai" },
      { value: "Kota Pekan Baru", label: "Kota Pekan Baru" },
      { value: "Kab. Kuantan Singingi", label: "Kab. Kuantan Singingi" },
      { value: "Kab. Siak", label: "Kab. Siak" },
      { value: "Kab. Rokan Hilir", label: "Kab. Rokan Hilir" },
      { value: "Kab. Rokan Hulu", label: "Kab. Rokan Hulu" },
      { value: "Kab. Pelalawan", label: "Kab. Pelalawan" },
      { value: "Kab. Indragiri Hilir", label: "Kab. Indragiri Hilir" },
      { value: "Kab. Bengkalis", label: "Kab. Bengkalis" },
      { value: "Kab. Indragiri Hulu", label: "Kab. Indragiri Hulu" },
      { value: "Kab. Kampar", label: "Kab. Kampar" },
    ],
  },
  {
    value: "Jambi",
    cities: [
      { value: "Kab. Kerinci", label: "Kab. Kerinci" },
      { value: "Kab. Tebo", label: "Kab. Tebo" },
      { value: "Kab. Bungo", label: "Kab. Bungo" },
      {
        value: "Kab. Tanjung Jabung Timur",
        label: "Kab. Tanjung Jabung Timur",
      },
      {
        value: "Kab. Tanjung Jabung Barat",
        label: "Kab. Tanjung Jabung Barat",
      },
      { value: "Kab. Muaro Jambi", label: "Kab. Muaro Jambi" },
      {
        value: "Kab. Batanghari",
        label: "Kab. Batanghari",
      },
      { value: "Kab. Sarolangun", label: "Kab. Sarolangun" },
      { value: "Kab. Merangin", label: "Kab. Merangin" },
      {
        value: "Kota Jambi",
        cities: [
          { value: "Selamat", label: "Selamat" },
          { value: "Pematang Sulur", label: "Pematang Sulur" },
          { value: "Simpang Empat Sipin", label: "Simpang Empat Sipin" },
          { value: "Penyengat Rendah", label: "Penyengat Rendah" },
          { value: "Teluk Kenali", label: "Teluk Kenali" },
          { value: "Buluran Kenali", label: "Buluran Kenali" },
          { value: "Telanaipura", label: "Telanaipura" },
          { value: "Sungai Putri", label: "Sungai Putri" },
          { value: "Solok Sipin", label: "Solok Sipin" },
          { value: "Murni", label: "Murni" },
          { value: "Legok", label: "Legok" },
          { value: "Tanjung Johor", label: "Tanjung Johor" },
          { value: "Tahtul Yaman", label: "Tahtul Yaman" },
          { value: "Tengah", label: "Tengah" },
          { value: "Jelmu", label: "Jelmu" },
          { value: "Mudung Laut", label: "Mudung Laut" },
          { value: "Arab Melayu", label: "Arab Melayu" },
          { value: "Sungai Asam", label: "Sungai Asam" },
          { value: "Pasar Jambi", label: "Pasar Jambi" },
          { value: "Beringin", label: "Beringin" },
          { value: "Orang Kayo Hitam ", label: "Orang Kayo Hitam " },
          { value: "Mayang Mangurai", label: "Mayang Mangurai" },
          { value: "Kenali Besar", label: "Kenali Besar" },
          { value: "Beliung Patah", label: "Beliung Patah" },
          { value: "Bagan Pete", label: "Bagan Pete" },
          { value: "Paal Lima", label: "Paal Lima" },
          { value: "Kenali Asam Bawah", label: "Kenali Asam Bawah" },
          { value: "Kenali Asam Atas", label: "Kenali Asam Atas" },
          { value: "Suka Karya", label: "Suka Karya" },
          { value: "Simpang Tiga Sipin", label: "Simpang Tiga Sipin" },
          { value: "Rawa Sari", label: "Rawa Sari" },
          { value: "Kebun Handil", label: "Kebun Handil" },
          { value: "Handil Jaya", label: "Handil Jaya" },
          { value: "Jelutung", label: "Jelutung" },
          { value: "Payo Lebar", label: "Payo Lebar" },
          { value: "Lebak Bandung", label: "Lebak Bandung" },
          { value: "Cempaka Putih", label: "Cempaka Putih" },
          { value: "Talang Jauh", label: "Talang Jauh" },
          { value: "Sijenjang ", label: "Sijenjang " },
          { value: "Selincah", label: "Selincah" },
          { value: "Tanjung Sari", label: "Tanjung Sari" },
          { value: "Tanjung Pinang", label: "Tanjung Pinang" },
          { value: "Budiman", label: "Budiman" },
          { value: "Sulan Jana", label: "Sulan Jana" },
          { value: "Rajawali", label: "Rajawali" },
          { value: "Talang Banjar", label: "Talang Banjar" },
          { value: "Kasang Jaya", label: "Kasang Jaya" },
          { value: "Kasang", label: "Kasang" },
          { value: "Tambak Sari", label: "Tambak Sari" },
          { value: "Talang Bakung", label: "Talang Bakung" },
          { value: "Pasir Putih", label: "Pasir Putih" },
          { value: "Paal Merah", label: "Paal Merah" },
          { value: "Lingkar Selatan", label: "Lingkar Selatan" },
          { value: "Eka Jaya", label: "Eka Jaya" },
          { value: "The Hok", label: "The Hok" },
          { value: "Pakuan Baru", label: "Pakuan Baru" },
          { value: "Wijaya Pura", label: "Wijaya Pura" },
          { value: "Tanjung Raden", label: "Tanjung Raden" },
          { value: "Tanjung Pasir", label: "Tanjung Pasir" },
          { value: "Olak Kemang", label: "Olak Kemang" },
          { value: "Ulu Gedong", label: "Ulu Gedong" },
        ],
      },
    ],
  },
  {
    value: "Sumatera Selatan",
    cities: [
      { value: "Kota Prabumulih", label: "Kota Prabumulih" },
      { value: "Kota Lubuk Linggau", label: "Kota Lubuk Linggau" },
      { value: "Kota Pagar Alam", label: "Kota Pagar Alam" },
      { value: "Kota Palembang", label: "Kota Palembang" },
      { value: "Kab. Ogan Ilir ", label: "Kab. Ogan Ilir " },
      { value: "Kab. Oku Selatan ", label: "Kab. Oku Selatan " },
      { value: "Kab. Oku Timur ", label: "Kab. Oku Timur " },
      { value: "Kab. Banyuasin", label: "Kab. Banyuasin" },
      { value: "Kab. Musi Banyuasin", label: "Kab. Musi Banyuasin" },
      { value: "Kab. Musi Rawas", label: "Kab. Musi Rawas" },
      { value: "Kab. Lahat", label: "Kab. Lahat" },
      { value: "Kab. Muara Enim", label: "Kab. Muara Enim" },
      { value: "Kab. Ogan Komering Ilir ", label: "Kab. Ogan Komering Ilir " },
      { value: "Kab. Ogan Komering Ulu ", label: "Kab. Ogan Komering Ulu " },
    ],
  },
  {
    value: "Bengkulu",
    cities: [
      { value: "Kota Bengkulu", label: "Kota Bengkulu" },
      { value: "Kab. Kepahiang ", label: "Kab. Kepahiang " },
      { value: "Kab. Lebong ", label: "Kab. Lebong " },
      { value: "Kab. Muko Muko", label: "Kab. Muko Muko" },
      { value: "Kab. Seluma", label: "Kab. Seluma" },
      { value: "Kab. Kaur", label: "Kab. Kaur" },
      { value: "Kab. Bengkulu Utara", label: "Kab. Bengkulu Utara" },
      { value: "Kab. Rejang Lebong ", label: "Kab. Rejang Lebong " },
      { value: "Kab. Bengkulu Selatan", label: "Kab. Bengkulu Selatan" },
    ],
  },
  {
    value: "Lampung",
    cities: [
      { value: "Kota Metro", label: "Kota Metro" },
      { value: "Kota Bandar Lampung", label: "Kota Bandar Lampung" },
      { value: "Kab. Way Kanan", label: "Kab. Way Kanan" },
      { value: "Kab. Lampung Timur", label: "Kab. Lampung Timur" },
      { value: "Kab. Tanggamus", label: "Kab. Tanggamus" },
      { value: "Kab. Tulang Bawang", label: "Kab. Tulang Bawang" },
      { value: "Kab. Lampung Barat", label: "Kab. Lampung Barat" },
      { value: "Kab. Lampung Utara", label: "Kab. Lampung Utara" },
      { value: "Kab. Lampung Tengah", label: "Kab. Lampung Tengah" },
      { value: "Kab. Lampung Selatan", label: "Kab. Lampung Selatan" },
    ],
  },
  {
    value: "Kep Bangka Belitung",
    cities: [
      { value: "Kota Pangkal Pinang", label: "Kota Pangkal Pinang" },
      { value: "Kab. Bangka Timur", label: "Kab. Bangka Timur" },
      { value: "Kab. Bangka Barat", label: "Kab. Bangka Barat" },
      { value: "Kab. Bangka Tengah", label: "Kab. Bangka Tengah" },
      { value: "Kab. Bangka Selatan", label: "Kab. Bangka Selatan" },
      { value: "Kab. Belitung", label: "Kab. Belitung" },
      { value: "Kab. Bangka", label: "Kab. Bangka" },
    ],
  },
  {
    value: "Kep Riau",
    cities: [
      { value: "Kota Tanjung Pinang", label: "Kota Tanjung Pinang" },
      { value: "Kota Batam", label: "Kota Batam" },
      { value: "Kab. Lingga ", label: "Kab. Lingga " },
      { value: "Kab. Natuna", label: "Kab. Natuna" },
      { value: "Kab. Karimun", label: "Kab. Karimun" },
      { value: "Kab. Kepulauan Riau ", label: "Kab. Kepulauan Riau " },
    ],
  },
  {
    value: "Dki Jakarta",
    cities: [
      { value: "Kodya Jakarta Timur", label: "Kodya Jakarta Timur" },
      { value: "Kodya Jakarta Selatan", label: "Kodya Jakarta Selatan" },
      { value: "Kodya Jakarta Barat", label: "Kodya Jakarta Barat" },
      { value: "Kodya Jakarta Utara", label: "Kodya Jakarta Utara" },
      { value: "Kodya Jakarta Pusat", label: "Kodya Jakarta Pusat" },
      { value: "Kab.adm.kep.seribu", label: "Kab.adm.kep.seribu" },
    ],
  },
  {
    value: "Jawa Barat",
    cities: [
      { value: "Kota Banjar", label: "Kota Banjar" },
      { value: "Kota Tasikmalaya", label: "Kota Tasikmalaya" },
      { value: "Kota Cimahi", label: "Kota Cimahi" },
      { value: "Kota Depok", label: "Kota Depok" },
      { value: "Kota Bekasi", label: "Kota Bekasi" },
      { value: "Kota Cirebon", label: "Kota Cirebon" },
      { value: "Kota Bandung", label: "Kota Bandung" },
      { value: "Kota Sukabumi", label: "Kota Sukabumi" },
      { value: "Kota Bogor", label: "Kota Bogor" },
      { value: "Kab. Bekasi", label: "Kab. Bekasi" },
      { value: "Kab. Karawang", label: "Kab. Karawang" },
      { value: "Kab. Purwakarta", label: "Kab. Purwakarta" },
      { value: "Kab. Subang", label: "Kab. Subang" },
      { value: "Kab. Indramayu", label: "Kab. Indramayu" },
      { value: "Kab. Sumedang", label: "Kab. Sumedang" },
      { value: "Kab. Majalengka", label: "Kab. Majalengka" },
      { value: "Kab. Cirebon", label: "Kab. Cirebon" },
      { value: "Kab. Kuningan", label: "Kab. Kuningan" },
      { value: "Kab. Ciamis", label: "Kab. Ciamis" },
      { value: "Kab. Tasikmalaya", label: "Kab. Tasikmalaya" },
      { value: "Kab. Garut", label: "Kab. Garut" },
      { value: "Kab. Bandung", label: "Kab. Bandung" },
      { value: "Kab. Cianjur", label: "Kab. Cianjur" },
      { value: "Kab. Sukabumi", label: "Kab. Sukabumi" },
      { value: "Kab. Bogor", label: "Kab. Bogor" },
    ],
  },
  {
    value: "Jawa Tengah",
    cities: [
      { value: "Kota Tegal", label: "Kota Tegal" },
      { value: "Kota Pekalongan", label: "Kota Pekalongan" },
      {
        value: "Kota Semarang",
        cities: [
          { value: "Kec. Tugu", label: "Kec. Tugu" },
          { value: "Kec. Ngaliyan", label: "Kec. Ngaliyan" },
          { value: "Kec. Mijen", label: "Kec. Mijen" },
          { value: "Kec. Gunung Pati", label: "Kec. Gunung Pati" },
          { value: "Kec. Semarang Barat", label: "Kec. Semarang Barat" },
          { value: "Kec. Semarang Utara", label: "Kec. Semarang Utara" },
          { value: "Kec. Genuk", label: "Kec. Genuk" },
          { value: "Kec. Pedurungan", label: "Kec. Pedurungan" },
          { value: "Kec. Gayamsari", label: "Kec. Gayamsari" },
          { value: "Kec. Semarang Timur", label: "Kec. Semarang Timur" },
          { value: "Kec. Semarang Tengah", label: "Kec. Semarang Tengah" },
          { value: "Kec. Semarang Selatan", label: "Kec. Semarang Selatan" },
          { value: "Kec. Gajah Mungkur", label: "Kec. Gajah Mungkur" },
          { value: "Kec. Candisari", label: "Kec. Candisari" },
          { value: "Kec. Tembalang", label: "Kec. Tembalang" },
          { value: "Kec. Banyumanik", label: "Kec. Banyumanik" },
        ],
      },

      { value: "Kota Salatiga", label: "Kota Salatiga" },
      { value: "Kota Surakarta", label: "Kota Surakarta" },
      { value: "Kota Magelang", label: "Kota Magelang" },
      { value: "Kab. Brebes", label: "Kab. Brebes" },
      { value: "Kab. Tegal", label: "Kab. Tegal" },
      { value: "Kab. Pemalang", label: "Kab. Pemalang" },
      { value: "Kab. Pekalongan", label: "Kab. Pekalongan" },
      {
        value: "Kab. Batang",
        cities: [
          { value: "Kec. Wonotunggal", label: "Kec. Wonotunggal" },
          { value: "Kec. Bandar", label: "Kec. Bandar" },
          { value: "Kec. Blado", label: "Kec. Blado" },
          { value: "Kec. Reban", label: "Kec. Reban" },
          { value: "Kec. Bawang", label: "Kec. Bawang" },
          { value: "Kec. Tersono", label: "Kec. Tersono" },
          { value: "Kec. Gringsing", label: "Kec. Gringsing" },
          { value: "Kec. Limpung", label: "Kec. Limpung" },
          { value: "Kec. Subah", label: "Kec. Subah" },
          { value: "Kec. Tulis", label: "Kec. Tulis" },
          { value: "Kec. Batang", label: "Kec. Batang" },
          { value: "Kec. Warungasem", label: "Kec. Warungasem" },
          { value: "Kec. Kandeman", label: "Kec. Kandeman" },
          { value: "Kec. Pecalungan", label: "Kec. Pecalungan" },
          { value: "Kec. Banyuputih", label: "Kec. Banyuputih" },
        ],
      },
      { value: "Kab. Kendal", label: "Kab. Kendal" },
      { value: "Kab. Temanggung", label: "Kab. Temanggung" },
      { value: "Kab. Semarang", label: "Kab. Semarang" },
      { value: "Kab. Demak", label: "Kab. Demak" },
      { value: "Kab. Jepara", label: "Kab. Jepara" },
      { value: "Kab. Kudus", label: "Kab. Kudus" },
      { value: "Kab. Pati", label: "Kab. Pati" },
      { value: "Kab. Rembang", label: "Kab. Rembang" },
      {
        value: "Kab. Blora",
        cities: [
          { value: "Kec. Blora", label: "Kec. Blora" },
          { value: "Kec. Jepon", label: "Kec. Jepon" },
          { value: "Kec. Bogorejo", label: "Kec. Bogorejo" },
          { value: "Kec. Jiken", label: "Kec. Jiken" },
          { value: "Kec. Sambong", label: "Kec. Sambong" },
          { value: "Kec. Cepu", label: "Kec. Cepu" },
          { value: "Kec. Kedungtuban", label: "Kec. Kedungtuban" },
          { value: "Kec. Kradenan", label: "Kec. Kradenan" },
          { value: "Kec. Randublatung", label: "Kec. Randublatung" },
          { value: "Kec. Jati", label: "Kec. Jati" },
          { value: "Kec. Banjarejo", label: "Kec. Banjarejo" },
          { value: "Kec. Tunjungan", label: "Kec. Tunjungan" },
          { value: "Kec. Japah", label: "Kec. Japah" },
          { value: "Kec. Ngawen", label: "Kec. Ngawen" },
          { value: "Kec. Todanan", label: "Kec. Todanan" },
        ],
      },
      { value: "Kab. Grobogan", label: "Kab. Grobogan" },
      { value: "Kab. Sragen", label: "Kab. Sragen" },
      { value: "Kab. Karanganyar", label: "Kab. Karanganyar" },
      { value: "Kab. Wonogiri", label: "Kab. Wonogiri" },
      { value: "Kab. Sukoharjo", label: "Kab. Sukoharjo" },
      { value: "Kab. Klaten", label: "Kab. Klaten" },
      { value: "Kab. Boyolali", label: "Kab. Boyolali" },
      { value: "Kab. Magelang", label: "Kab. Magelang" },
      { value: "Kab. Wonosobo", label: "Kab. Wonosobo" },
      { value: "Kab. Purworejo", label: "Kab. Purworejo" },
      { value: "Kab. Kebumen", label: "Kab. Kebumen" },
      { value: "Kab. Banjarnegara", label: "Kab. Banjarnegara" },
      { value: "Kab. Purbalingga", label: "Kab. Purbalingga" },
      {
        value: "Kab. Banyumas",
        cities: [
          { value: "Kec. Patikraja", label: "Kec. Patikraja" },
          { value: "Kec. Kebasen", label: "Kec. Kebasen" },
          { value: "Kec. Sokaraja", label: "Kec. Sokaraja" },
          { value: "Kec. Sumpiuh", label: "Kec. Sumpiuh" },
          { value: "Kec. Tambak", label: "Kec. Tambak" },
          { value: "Kec. Gumelar", label: "Kec. Gumelar" },
          { value: "Kec. Pekuncen", label: "Kec. Pekuncen" },
          { value: "Kec. Jatilawang", label: "Kec. Jatilawang" },
          { value: "Kec. Sumbang", label: "Kec. Sumbang" },
          { value: "Kec. Baturraden", label: "Kec. Baturraden" },
          { value: "Kec. Wangon", label: "Kec. Wangon" },
          { value: "Kec. Somagede", label: "Kec. Somagede" },
          { value: "Kec. Ajibarang", label: "Kec. Ajibarang" },
          { value: "Kec. Karang Lewas", label: "Kec. Karang Lewas" },
          { value: "Kec. Kembaran", label: "Kec. Kembaran" },
          { value: "Kec. Kalibagor", label: "Kec. Kalibagor" },
        ],
      },
      { value: "Kab. Cilacap", label: "Kab. Cilacap" },
    ],
  },
  {
    value: "Di Jogjakarta",
    cities: [
      { value: "Kota Yogyakarta", label: "Kota Yogyakarta" },
      { value: "Kab. Sleman", label: "Kab. Sleman" },
      { value: "Kab. Gunung Kidul", label: "Kab. Gunung Kidul" },
      { value: "Kab. Bantul", label: "Kab. Bantul" },
      { value: "Kab. Kulon Progo", label: "Kab. Kulon Progo" },
    ],
  },
  {
    value: "Jawa Timur",
    cities: [
      { value: "Batu", label: "Batu" },
      { value: "Kota Surabaya", label: "Kota Surabaya" },
      { value: "Kota Madiun", label: "Kota Madiun" },
      { value: "Kota Mojokerto", label: "Kota Mojokerto" },
      { value: "Kota Pasuruan", label: "Kota Pasuruan" },
      { value: "Kota Probolinggo", label: "Kota Probolinggo" },
      { value: "Kota Malang", label: "Kota Malang" },
      { value: "Kota Blitar", label: "Kota Blitar" },
      { value: "Kota Kediri", label: "Kota Kediri" },
      { value: "Kab. Sumenep", label: "Kab. Sumenep" },
      { value: "Kab. Pamekasan", label: "Kab. Pamekasan" },
      { value: "Kab. Sampang", label: "Kab. Sampang" },
      { value: "Kab. Bangkalan", label: "Kab. Bangkalan" },
      { value: "Kab. Gresik", label: "Kab. Gresik" },
      { value: "Kab. Lamongan", label: "Kab. Lamongan" },
      { value: "Kab. Tuban", label: "Kab. Tuban" },
      { value: "Kab. Bojonegoro", label: "Kab. Bojonegoro" },
      { value: "Kab. Ngawi", label: "Kab. Ngawi" },
      { value: "Kab. Magetan", label: "Kab. Magetan" },
      { value: "Kab. Madiun", label: "Kab. Madiun" },
      { value: "Kab. Nganjuk", label: "Kab. Nganjuk" },
      { value: "Kab. Jombang", label: "Kab. Jombang" },
      { value: "Kab. Mojokerto", label: "Kab. Mojokerto" },
      { value: "Kab. Sidoarjo", label: "Kab. Sidoarjo" },
      { value: "Kab. Pasuruan", label: "Kab. Pasuruan" },
      { value: "Kab. Probolinggo", label: "Kab. Probolinggo" },
      { value: "Kab. Situbondo", label: "Kab. Situbondo" },
      { value: "Kab. Bondowoso", label: "Kab. Bondowoso" },
      {
        value: "Kab. Banyuwangi",
        cities: [
          { value: "Kec. Pesanggaran", label: "Kec. Pesanggaran" },
          { value: "Kec. Bangorejo", label: "Kec. Bangorejo" },
          { value: "Kec. Purwoharjo", label: "Kec. Purwoharjo" },
          { value: "Kec. Tegaldlimo", label: "Kec. Tegaldlimo" },
          { value: "Kec. Muncar", label: "Kec. Muncar" },
          { value: "Kec. Cluring", label: "Kec. Cluring" },
          { value: "Kec. Gambiran", label: "Kec. Gambiran" },
          { value: "Kec. Srono", label: "Kec. Srono" },
          { value: "Kec. Genteng", label: "Kec. Genteng" },
          { value: "Kec. Glenmore", label: "Kec. Glenmore" },
          { value: "Kec. Kalibaru", label: "Kec. Kalibaru" },
          { value: "Kec. Singojuruh", label: "Kec. Singojuruh" },
          { value: "Kec. Rogojampi", label: "Kec. Rogojampi" },
          { value: "Kec. Kabat", label: "Kec. Kabat" },
          { value: "Kec. Glagah", label: "Kec. Glagah" },
          { value: "Kec. Banyuwangi", label: "Kec. Banyuwangi" },
          { value: "Kec. Giri", label: "Kec. Giri" },
          { value: "Kec. Wongsorejo", label: "Kec. Wongsorejo" },
          { value: "Kec. Songgon", label: "Kec. Songgon" },
          { value: "Kec. Sempu", label: "Kec. Sempu" },
          { value: "Kec. Kalipuro", label: "Kec. Kalipuro" },
          { value: "Kec. Siliragung", label: "Kec. Siliragung" },
          { value: "Kec. Tegalsari", label: "Kec. Tegalsari" },
          { value: "Kec. Licin", label: "Kec. Licin" },
        ],
      },
      { value: "Kab. Jember", label: "Kab. Jember" },
      { value: "Kab. Lumajang", label: "Kab. Lumajang" },
      { value: "Kab. Malang", label: "Kab. Malang" },
      { value: "Kab. Kediri", label: "Kab. Kediri" },
      { value: "Kab. Blitar", label: "Kab. Blitar" },
      { value: "Kab. Tulungagung", label: "Kab. Tulungagung" },
      { value: "Kab. Trenggalek", label: "Kab. Trenggalek" },
      { value: "Kab. Ponorogo", label: "Kab. Ponorogo" },
      { value: "Kab. Pacitan", label: "Kab. Pacitan" },
    ],
  },
  {
    value: "Banten",
    cities: [
      { value: "Kota Cilegon", label: "Kota Cilegon" },
      { value: "Kota Tangerang", label: "Kota Tangerang" },
      { value: "Kab. Serang", label: "Kab. Serang" },
      { value: "Kab. Tangerang", label: "Kab. Tangerang" },
      { value: "Kab. Lebak", label: "Kab. Lebak" },
      { value: "Kab. Pandeglang", label: "Kab. Pandeglang" },
    ],
  },
  {
    value: "Bali",
    cities: [
      { value: "Kota Denpasar", label: "Kota Denpasar" },
      { value: "Kab. Buleleng", label: "Kab. Buleleng" },
      { value: "Kab. Karangasem", label: "Kab. Karangasem" },
      { value: "Kab. Bangli", label: "Kab. Bangli" },
      { value: "Kab. Klungkung", label: "Kab. Klungkung" },
      { value: "Kab. Gianyar", label: "Kab. Gianyar" },
      { value: "Kab. Badung", label: "Kab. Badung" },
      { value: "Kab. Tabanan", label: "Kab. Tabanan" },
      { value: "Kab. Jembarana", label: "Kab. Jembarana" },
    ],
  },
  {
    value: "Nusa Tenggara Barat",
    cities: [
      { value: "Kota Bima", label: "Kota Bima" },
      { value: "Kota Mataram", label: "Kota Mataram" },
      { value: "Kab. Sumbawa Barat", label: "Kab. Sumbawa Barat" },
      { value: "Kab. Bima", label: "Kab. Bima" },
      { value: "Kab. Dompu", label: "Kab. Dompu" },
      { value: "Kab. Sumbawa ", label: "Kab. Sumbawa " },
      { value: "Kab. Lombok Timur", label: "Kab. Lombok Timur" },
      { value: "Kab. Lombok Tengah", label: "Kab. Lombok Tengah" },
      { value: "Kab. Lombok Barat", label: "Kab. Lombok Barat" },
    ],
  },
  {
    value: "Nusa Tenggara Timur",
    cities: [
      { value: "Kota Kupang", label: "Kota Kupang" },
      { value: "Kab. Manggarai Barat", label: "Kab. Manggarai Barat" },
      { value: "Kab. Rote Ndao", label: "Kab. Rote Ndao" },
      { value: "Kab. Lembata", label: "Kab. Lembata" },
      { value: "Kab. Sumba Barat", label: "Kab. Sumba Barat" },
      { value: "Kab. Sumba Timur", label: "Kab. Sumba Timur" },
      { value: "Kab. Manggarai", label: "Kab. Manggarai" },
      { value: "Kab. Ngada", label: "Kab. Ngada" },
      { value: "Kab. Ende", label: "Kab. Ende" },
      { value: "Kab. Sikka", label: "Kab. Sikka" },
      { value: "Kab. Flores Timur", label: "Kab. Flores Timur" },
      { value: "Kab. Alor", label: "Kab. Alor" },
      { value: "Kab. Belu", label: "Kab. Belu" },
      { value: "Kab. Timor Tengah Utara", label: "Kab. Timor Tengah Utara" },
      {
        value: "Kab. Timor Tengah Selatan",
        label: "Kab. Timor Tengah Selatan",
      },
      { value: "Kab. Kupang", label: "Kab. Kupang" },
    ],
  },
  {
    value: "Kalimantan Barat",
    cities: [
      { value: "Kota Singkawang", label: "Kota Singkawang" },
      { value: "Kota Pontianak", label: "Kota Pontianak" },
      { value: "Kab. Sekadau ", label: "Kab. Sekadau " },
      { value: "Kab. Melawi ", label: "Kab. Melawi " },
      { value: "Kab. Landak", label: "Kab. Landak" },
      { value: "Kab. Bengkayang", label: "Kab. Bengkayang" },
      { value: "Kab. Kapuas Hulu", label: "Kab. Kapuas Hulu" },
      { value: "Kab. Sintang ", label: "Kab. Sintang " },
      { value: "Kab. Ketapang", label: "Kab. Ketapang" },
      { value: "Kab. Sanggau ", label: "Kab. Sanggau " },
      { value: "Kab. Pontianak", label: "Kab. Pontianak" },
      { value: "Kab. Sambas", label: "Kab. Sambas" },
    ],
  },
  {
    value: "Kalimantan Tengah",
    cities: [
      { value: "Kota Palangkaraya", label: "Kota Palangkaraya" },
      { value: "Kab. Barito Timur", label: "Kab. Barito Timur" },
      { value: "Kab. Murung Raya", label: "Kab. Murung Raya" },
      { value: "Kab. Pulang Pisau", label: "Kab. Pulang Pisau" },
      { value: "Kab. Gunung Mas", label: "Kab. Gunung Mas" },
      { value: "Kab. Lamandau", label: "Kab. Lamandau" },
      { value: "Kab. Sukamara", label: "Kab. Sukamara" },
      { value: "Kab. Seruyan", label: "Kab. Seruyan" },
      { value: "Kab. Katingin", label: "Kab. Katingin" },
      { value: "Kab. Barito Utara", label: "Kab. Barito Utara" },
      { value: "Kab. Barito Selatan", label: "Kab. Barito Selatan" },
      { value: "Kab. Kapuas", label: "Kab. Kapuas" },
      { value: "Kab. Kotawaringin Timur", label: "Kab. Kotawaringin Timur" },
      { value: "Kab. Kotawaringin Barat", label: "Kab. Kotawaringin Barat" },
    ],
  },
  {
    value: "Kalimanta Selatan",
    cities: [
      { value: "Kota Banjarbaru", label: "Kota Banjarbaru" },
      { value: "Kota Banjarmasin", label: "Kota Banjarmasin" },
      { value: "Kab. Balangan", label: "Kab. Balangan" },
      { value: "Kab. Tanah Bambu", label: "Kab. Tanah Bambu" },
      { value: "Kab. Tabalong", label: "Kab. Tabalong" },
      { value: "Kab. Hulu Sungai Utara", label: "Kab. Hulu Sungai Utara" },
      { value: "Kab. Hulu Sungai Tengah", label: "Kab. Hulu Sungai Tengah" },
      { value: "Kab. Hulu Sungai Selatan", label: "Kab. Hulu Sungai Selatan" },
      { value: "Kab. Tapin", label: "Kab. Tapin" },
      { value: "Kab. Barito Kuala", label: "Kab. Barito Kuala" },
      { value: "Kab. Banjar", label: "Kab. Banjar" },
      { value: "Kab. Kotabaru", label: "Kab. Kotabaru" },
      { value: "Kab. Tanah Laut", label: "Kab. Tanah Laut" },
    ],
  },
  {
    value: "Kalimantan Timur",
    cities: [
      { value: "Kota Bontang", label: "Kota Bontang" },
      { value: "Kota Tarakan", label: "Kota Tarakan" },
      { value: "Kota Samarinda", label: "Kota Samarinda" },
      { value: "Kota Balikpapan", label: "Kota Balikpapan" },
      { value: "Kab. Penajam Paser Utara", label: "Kab. Penajam Paser Utara" },
      { value: "Kab. Kutai Timur", label: "Kab. Kutai Timur" },
      { value: "Kab. Kutai Barat", label: "Kab. Kutai Barat" },
      { value: "Kab. Malinau", label: "Kab. Malinau" },
      { value: "Kab. Nunukan", label: "Kab. Nunukan" },
      { value: "Kab. Bulungan", label: "Kab. Bulungan" },
      { value: "Kab. Berau", label: "Kab. Berau" },
      { value: "Kab. Kutai Kertanegara", label: "Kab. Kutai Kertanegara" },
      { value: "Kab. Pasir", label: "Kab. Pasir" },
    ],
  },
  {
    value: "Sulawesi Utara",
    cities: [
      { value: "Kota Tomohon", label: "Kota Tomohon" },
      { value: "Kota Bitung", label: "Kota Bitung" },
      { value: "Kota Manado", label: "Kota Manado" },
      { value: "Kab. Minahasa Utara", label: "Kab. Minahasa Utara" },
      { value: "Kab. Minahasa Selatan", label: "Kab. Minahasa Selatan" },
      { value: "Kab. Kepulauan Talaud", label: "Kab. Kepulauan Talaud" },
      { value: "Kab. Kepulauan Sangihe", label: "Kab. Kepulauan Sangihe" },
      { value: "Kab. Minahasa ", label: "Kab. Minahasa " },
      { value: "Kab. Bolaang Mangondow", label: "Kab. Bolaang Mangondow" },
    ],
  },
  {
    value: "Sulawesi Tengah",
    cities: [
      { value: "Kota Palu", label: "Kota Palu" },
      { value: "Kab. Tojo Una Una", label: "Kab. Tojo Una Una" },
      { value: "Kab. Parigi Moutong", label: "Kab. Parigi Moutong" },
      { value: "Kab. Banggai Kepulauan", label: "Kab. Banggai Kepulauan" },
      { value: "Kab. Morowali", label: "Kab. Morowali" },
      { value: "Kab. Buol", label: "Kab. Buol" },
      { value: "Kab. Toloi Toli", label: "Kab. Toloi Toli" },
      { value: "Kab. Donggala", label: "Kab. Donggala" },
      { value: "Kab. Poso ", label: "Kab. Poso " },
      { value: "Kab. Banggai", label: "Kab. Banggai" },
    ],
  },
  {
    value: "Sulawesi Selatan",
    cities: [
      { value: "Kota Palopo", label: "Kota Palopo" },
      { value: "Kota Pare Pare", label: "Kota Pare Pare" },
      { value: "Kota Makasar", label: "Kota Makasar" },
      { value: "Kab. Luwu Timur", label: "Kab. Luwu Timur" },
      { value: "Kab. Luwu Utara", label: "Kab. Luwu Utara" },
      { value: "Kab. Tana Toraja", label: "Kab. Tana Toraja" },
      { value: "Kab. Luwu", label: "Kab. Luwu" },
      { value: "Kab. Enrekang", label: "Kab. Enrekang" },
      { value: "Kab. Pinrang", label: "Kab. Pinrang" },
      { value: "Kab. Sidenreng Rapang", label: "Kab. Sidenreng Rapang" },
      { value: "Kab. Wajo", label: "Kab. Wajo" },
      { value: "Kab. Soppeng", label: "Kab. Soppeng" },
      { value: "Kab. Barru", label: "Kab. Barru" },
      { value: "Kab. Pangkajene Kep.", label: "Kab. Pangkajene Kep." },
      { value: "Kab. Maros", label: "Kab. Maros" },
      { value: "Kab. Bone", label: "Kab. Bone" },
      { value: "Kab. Sinjai", label: "Kab. Sinjai" },
      { value: "Kab. Gowa", label: "Kab. Gowa" },
      { value: "Kab. Takalar", label: "Kab. Takalar" },
      { value: "Kab. Jeneponto.", label: "Kab. Jeneponto." },
      { value: "Kab. Bantaeng", label: "Kab. Bantaeng" },
      { value: "Kab. Bulukumba", label: "Kab. Bulukumba" },
      { value: "Kab. Selayar", label: "Kab. Selayar" },
    ],
  },
  {
    value: "Sulawesi Tenggara",
    cities: [
      { value: "Kota Bau Bau", label: "Kota Bau Bau" },
      { value: "Kota Kendari", label: "Kota Kendari" },
      { value: "Kab. Kolaka Utara", label: "Kab. Kolaka Utara" },
      { value: "Kab. Wakatobi", label: "Kab. Wakatobi" },
      { value: "Kab. Bombana", label: "Kab. Bombana" },
      { value: "Kab. Konawe Selatan", label: "Kab. Konawe Selatan" },
      { value: "Kab. Buton", label: "Kab. Buton" },
      { value: "Kab. Muna", label: "Kab. Muna" },
      { value: "Kab. Konawe", label: "Kab. Konawe" },
      { value: "Kab. Kolaka", label: "Kab. Kolaka" },
    ],
  },
  {
    value: "Gorontalo ",
    cities: [
      {
        value: "Kota Gorontalo",
        cities: [
          { value: "Kota Selatan", label: "Kota Selatan" },
          { value: "Kota Utara", label: "Kota Utara" },
          { value: "Kota Barat", label: "Kota Barat" },
          { value: "Kota Timur", label: "Kota Timur" },
          { value: "Kota Tengah", label: "Kota Tengah" },
          { value: "Dungingi", label: "Dungingi" },
          { value: "Dumbo Raya", label: "Dumbo Raya" },
          { value: "Hulonthalangi", label: "Hulonthalangi" },
          { value: "Sipatana", label: "Sipatana" },
        ],
      },
      {
        value: "Kab. Pohuwato",
        cities: [
          { value: "Buntulia", label: "Buntulia" },
          { value: "Dengilo", label: "Dengilo" },
          { value: "Duhiadaa", label: "Duhiadaa" },
          { value: "Lemito", label: "Lemito" },
          { value: "Marisa", label: "Marisa" },
          { value: "Paguat", label: "Paguat" },
          { value: "Patilanggio", label: "Patilanggio" },
          { value: "Popayato", label: "Popayato" },
          { value: "Popayato Barat", label: "Popayato Barat" },
          { value: "Popayato Timur", label: "Popayato Timur" },
          { value: "Randangan", label: "Randangan" },
          { value: "Taluditi", label: "Taluditi" },
          { value: "Wanggarasi", label: "Wanggarasi" },
        ],
      },
      {
        value: "Kab. Bone Bolango",
        cities: [
          { value: "Bone", label: "Bone" },
          { value: "Bone Raya", label: "Bone Raya" },
          { value: "Bone Pantai", label: "Bone Pantai" },
          { value: "Botu Pingge", label: "Botu Pingge" },
          { value: "Bulango Selatan", label: "Bulango Selatan" },
          { value: "Bulango Timur", label: "Bulango Timur" },
          { value: "Bulango Ulu", label: "Bulango Ulu" },
          { value: "Bulango Utara", label: "Bulango Utara" },
          { value: "Bulawa", label: "Bulawa" },
          { value: "Kabila", label: "Kabila" },
          { value: "Kabila Bone", label: "Kabila Bone" },
          { value: "Pinogu", label: "Pinogu" },
          { value: "Suwawa", label: "Suwawa" },
          { value: "Suwawa Selatan", label: "Suwawa Selatan" },
          { value: "Suwawa Tengah", label: "Suwawa Tengah" },
          { value: "Suwawa Timur", label: "Suwawa Timur" },
          { value: "Tapa", label: "Tapa" },
          { value: "Tilongkabila", label: "Tilongkabila" },
        ],
      },
      {
        value: "Kab. Boalemo",
        cities: [
          { value: "Botumoito", label: "Botumoito" },
          { value: "Dulupi", label: "Dulupi" },
          { value: "Mananggu", label: "Mananggu" },
          { value: "Paguyaman", label: "Paguyaman" },
          { value: "Paguyaman Pantai", label: "Paguyaman Pantai" },
          { value: "Tilamuta", label: "Tilamuta" },
          { value: "Wonosari", label: "Wonosari" },
        ],
      },
      {
        value: "Kab. Gorontalo",
        cities: [
          { value: "Asparaga", label: "Asparaga" },
          { value: "Dungaliyo", label: "Dungaliyo" },
          { value: "Batudaa", label: "Batudaa" },
          { value: "Batudaa Pantai", label: "Batudaa Pantai" },
          { value: "Bilato", label: "Bilato" },
          { value: "Biluhu", label: "Biluhu" },
          { value: "Boliyohuto", label: "Boliyohuto" },
          { value: "Bongomeme", label: "Bongomeme" },
          { value: "Limboto", label: "Limboto" },
          { value: "Limboto Barat", label: "Limboto Barat" },
          { value: "Mootilango", label: "Mootilango" },
          { value: "Pulubala", label: "Pulubala" },
          { value: "Tabongo", label: "Tabongo" },
          { value: "Telaga", label: "Telaga" },
          { value: "Telaga Biru", label: "Telaga Biru" },
          { value: "Telaga Jaya", label: "Telaga Jaya" },
          { value: "Tibawa", label: "Tibawa" },
          { value: "Tilango", label: "Tilango" },
          { value: "Tolangohula", label: "Tolangohula" },
        ],
      },
      {
        value: "Kab. Gorontalo Utara",
        cities: [
          { value: "Anggrek", label: "Anggrek" },
          { value: "Atinggola", label: "Atinggola" },
          { value: "Biau", label: "Biau" },
          { value: "Gentuma Raya", label: "Gentuma Raya" },
          { value: "Kwandang", label: "Kwandang" },
          { value: "Monano", label: "Monano" },
          { value: "Ponelo Kepulauan", label: "Ponelo Kepulauan" },
          { value: "Sumalata", label: "Sumalata" },
          { value: "Sumalata Timur", label: "Sumalata Timur" },
          { value: "Tolinggula", label: "Tolinggula" },
          { value: "Tomilito", label: "Tomilito" },
        ],
      },
    ],
  },
  {
    value: "Sulawesi Barat",
    cities: [
      { value: "Kab. Majene", label: "Kab. Majene" },
      { value: "Kab. Polowali Mamasa", label: "Kab. Polowali Mamasa" },
      { value: "Kab. Mamasa", label: "Kab. Mamasa" },
      { value: "Kab. Mamuju", label: "Kab. Mamuju" },
      { value: "Kab. Mamuju Utara", label: "Kab. Mamuju Utara" },
    ],
  },
  {
    value: "Maluku",
    cities: [
      { value: "Kota Ambon", label: "Kota Ambon" },
      { value: "Kab. Kepulauan Aru", label: "Kab. Kepulauan Aru" },
      { value: "Kab. Seram Bagian Barat ", label: "Kab. Seram Bagian Barat " },
      { value: "Kab. Seram Bagian Timur", label: "Kab. Seram Bagian Timur" },
      { value: "Kab. Buru", label: "Kab. Buru" },
      { value: "Kab. Maluku Tenggara Brt", label: "Kab. Maluku Tenggara Brt" },
      { value: "Kab. Maluku Tenggara ", label: "Kab. Maluku Tenggara " },
      { value: "Kab. Maluku Tengah ", label: "Kab. Maluku Tengah " },
    ],
  },
  {
    value: "Maluku Utara",
    cities: [
      { value: "Kota Tidore Kepulauan", label: "Kota Tidore Kepulauan" },
      { value: "Kota Ternate", label: "Kota Ternate" },
      { value: "Kab. Halmahera Timur", label: "Kab. Halmahera Timur" },
      { value: "Kab. Kepulauan Sula", label: "Kab. Kepulauan Sula" },
      { value: "Kab. Halmahera Selatan", label: "Kab. Halmahera Selatan" },
      { value: "Kab. Halmahera Utara", label: "Kab. Halmahera Utara" },
      { value: "Kab. Halmahera Tengah", label: "Kab. Halmahera Tengah" },
      { value: "Kab. Halmahera Barat", label: "Kab. Halmahera Barat" },
    ],
  },
  {
    value: "Papua",
    cities: [
      { value: "Kota Jayapura", label: "Kota Jayapura" },
      { value: "Kab. Supiori", label: "Kab. Supiori" },
      { value: "Kab. Asmat", label: "Kab. Asmat" },
      { value: "Kab. Mappi", label: "Kab. Mappi" },
      { value: "Kab. Boven Digoel", label: "Kab. Boven Digoel" },
      { value: "Kab. Waropen", label: "Kab. Waropen" },
      { value: "Kab. Tolikara", label: "Kab. Tolikara" },
      { value: "Kab. Yahukimo", label: "Kab. Yahukimo" },
      { value: "Kab. Pegunungan Bintang", label: "Kab. Pegunungan Bintang" },
      { value: "Kab. Keerom", label: "Kab. Keerom" },
      { value: "Kab. Sarmi", label: "Kab. Sarmi" },
      { value: "Kab. Mimika", label: "Kab. Mimika" },
      { value: "Kab. Paniai", label: "Kab. Paniai" },
      { value: "Kab. Puncak Jaya", label: "Kab. Puncak Jaya" },
      { value: "Kab. Biak Numfor", label: "Kab. Biak Numfor" },
      { value: "Kab. Yapen Waropen", label: "Kab. Yapen Waropen" },
      { value: "Kab. Nabire", label: "Kab. Nabire" },
      { value: "Kab. Jayapura", label: "Kab. Jayapura" },
      { value: "Kab. Jayawijaya", label: "Kab. Jayawijaya" },
      { value: "Kab. Merauke", label: "Kab. Merauke" },
    ],
  },
  {
    value: "Papua Barat",
    cities: [
      { value: "Kota Sorong", label: "Kota Sorong" },
      { value: "Kab. Kaima", label: "Kab. Kaima" },
      { value: "Kab. Teluk Wondama", label: "Kab. Teluk Wondama" },
      { value: "Kab. Teluk Bentuni", label: "Kab. Teluk Bentuni" },
      { value: "Kab. Raja Ampat", label: "Kab. Raja Ampat" },
      { value: "Kab. Sorong Selatan", label: "Kab. Sorong Selatan" },
      { value: "Kab. Fak Fak", label: "Kab. Fak Fak" },
      { value: "Kab. Manokwari", label: "Kab. Manokwari" },
      { value: "Kab. Sorong", label: "Kab. Sorong" },
    ],
  },
];
