export const countries = [
  { code: "AD", value: "Andorra", label: "AD - Andorra", phone: "376" },
  {
    code: "AE",
    value: "United Arab Emirates",
    label: "AE - United Arab Emirates",
    phone: "971",
  },
  { code: "AF", value: "Afghanistan", label: "AF - Afghanistan", phone: "93" },
  {
    code: "AG",
    value: "Antigua and Barbuda",
    label: "AG - Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AI", value: "Anguilla", label: "AI - Anguilla", phone: "1-264" },
  { code: "AL", value: "Albania", label: "AL - Albania", phone: "355" },
  { code: "AM", value: "Armenia", label: "AM - Armenia", phone: "374" },
  { code: "AO", value: "Angola", label: "AO - Angola", phone: "244" },
  { code: "AQ", value: "Antarctica", label: "AQ - Antarctica", phone: "672" },
  { code: "AR", value: "Argentina", label: "AR - Argentina", phone: "54" },
  {
    code: "AS",
    value: "American Samoa",
    label: "AS - American Samoa",
    phone: "1-684",
  },
  { code: "AT", value: "Austria", label: "AT - Austria", phone: "43" },
  { code: "AU", value: "Australia", label: "AU - Australia", phone: "61" },
  { code: "AW", value: "Aruba", label: "AW - Aruba", phone: "297" },
  {
    code: "AX",
    value: "Alland Islands",
    label: "AX - Alland Islands",
    phone: "358",
  },
  { code: "AZ", value: "Azerbaijan", label: "AZ - Azerbaijan", phone: "994" },
  {
    code: "BA",
    value: "Bosnia and Herzegovina",
    label: "BA - Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BB", value: "Barbados", label: "BB - Barbados", phone: "1-246" },
  { code: "BD", value: "Bangladesh", label: "BD - Bangladesh", phone: "880" },
  { code: "BE", value: "Belgium", label: "BE - Belgium", phone: "32" },
  {
    code: "BF",
    value: "Burkina Faso",
    label: "BF - Burkina Faso",
    phone: "226",
  },
  { code: "BG", value: "Bulgaria", label: "BG - Bulgaria", phone: "359" },
  { code: "BH", value: "Bahrain", label: "BH - Bahrain", phone: "973" },
  { code: "BI", value: "Burundi", label: "BI - Burundi", phone: "257" },
  { code: "BJ", value: "Benin", label: "BJ - Benin", phone: "229" },
  {
    code: "BL",
    value: "Saint Barthelemy",
    label: "BL - Saint Barthelemy",
    phone: "590",
  },
  { code: "BM", value: "Bermuda", label: "BM - Bermuda", phone: "1-441" },
  {
    code: "BN",
    value: "Brunei Darussalam",
    label: "BN - Brunei Darussalam",
    phone: "673",
  },
  { code: "BO", value: "Bolivia", label: "BO - Bolivia", phone: "591" },
  { code: "BR", value: "Brazil", label: "BR - Brazil", phone: "55" },
  { code: "BS", value: "Bahamas", label: "BS - Bahamas", phone: "1-242" },
  { code: "BT", value: "Bhutan", label: "BT - Bhutan", phone: "975" },
  {
    code: "BV",
    value: "Bouvet Island",
    label: "BV - Bouvet Island",
    phone: "47",
  },
  { code: "BW", value: "Botswana", label: "BW - Botswana", phone: "267" },
  { code: "BY", value: "Belarus", label: "BY - Belarus", phone: "375" },
  { code: "BZ", value: "Belize", label: "BZ - Belize", phone: "501" },
  { code: "CA", value: "Canada", label: "CA - Canada", phone: "1" },
  {
    code: "CC",
    value: "Cocos (Keeling) Islands",
    label: "CC - Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    value: "Congo, Republic of the",
    label: "CD - Congo, Republic of the",
    phone: "242",
  },
  {
    code: "CF",
    value: "Central African Republic",
    label: "CF - Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    value: "Congo, Democratic Republic of the",
    label: "CG - Congo, Democratic Republic of the",
    phone: "243",
  },
  { code: "CH", value: "Switzerland", label: "CH - Switzerland", phone: "41" },
  {
    code: "CI",
    value: "Cote d'Ivoire",
    label: "CI - Cote d'Ivoire",
    phone: "225",
  },
  {
    code: "CK",
    value: "Cook Islands",
    label: "CK - Cook Islands",
    phone: "682",
  },
  { code: "CL", value: "Chile", label: "CL - Chile", phone: "56" },
  { code: "CM", value: "Cameroon", label: "CM - Cameroon", phone: "237" },
  { code: "CN", value: "China", label: "CN - China", phone: "86" },
  { code: "CO", value: "Colombia", label: "CO - Colombia", phone: "57" },
  { code: "CR", value: "Costa Rica", label: "CR - Costa Rica", phone: "506" },
  { code: "CU", value: "Cuba", label: "CU - Cuba", phone: "53" },
  { code: "CV", value: "Cape Verde", label: "CV - Cape Verde", phone: "238" },
  { code: "CW", value: "Curacao", label: "CW - Curacao", phone: "599" },
  {
    code: "CX",
    value: "Christmas Island",
    label: "CX - Christmas Island",
    phone: "61",
  },
  { code: "CY", value: "Cyprus", label: "CY - Cyprus", phone: "357" },
  {
    code: "CZ",
    value: "Czech Republic",
    label: "CZ - Czech Republic",
    phone: "420",
  },
  { code: "DE", value: "Germany", label: "DE - Germany", phone: "49" },
  { code: "DJ", value: "Djibouti", label: "DJ - Djibouti", phone: "253" },
  { code: "DK", value: "Denmark", label: "DK - Denmark", phone: "45" },
  { code: "DM", value: "Dominica", label: "DM - Dominica", phone: "1-767" },
  {
    code: "DO",
    value: "Dominican Republic",
    label: "DO - Dominican Republic",
    phone: "1-809",
  },
  { code: "DZ", value: "Algeria", label: "DZ - Algeria", phone: "213" },
  { code: "EC", value: "Ecuador", label: "EC - Ecuador", phone: "593" },
  { code: "EE", value: "Estonia", label: "EE - Estonia", phone: "372" },
  { code: "EG", value: "Egypt", label: "EG - Egypt", phone: "20" },
  {
    code: "EH",
    value: "Western Sahara",
    label: "EH - Western Sahara",
    phone: "212",
  },
  { code: "ER", value: "Eritrea", label: "ER - Eritrea", phone: "291" },
  { code: "ES", value: "Spain", label: "ES - Spain", phone: "34" },
  { code: "ET", value: "Ethiopia", label: "ET - Ethiopia", phone: "251" },
  { code: "FI", value: "Finland", label: "FI - Finland", phone: "358" },
  { code: "FJ", value: "Fiji", label: "FJ - Fiji", phone: "679" },
  {
    code: "FK",
    value: "Falkland Islands (Malvinas)",
    label: "FK - Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    value: "Micronesia, Federated States of",
    label: "FM - Micronesia, Federated States of",
    phone: "691",
  },
  {
    code: "FO",
    value: "Faroe Islands",
    label: "FO - Faroe Islands",
    phone: "298",
  },
  { code: "FR", value: "France", label: "FR - France", phone: "33" },
  { code: "GA", value: "Gabon", label: "GA - Gabon", phone: "241" },
  {
    code: "GB",
    value: "United Kingdom",
    label: "GB - United Kingdom",
    phone: "44",
  },
  { code: "GD", value: "Grenada", label: "GD - Grenada", phone: "1-473" },
  { code: "GE", value: "Georgia", label: "GE - Georgia", phone: "995" },
  {
    code: "GF",
    value: "French Guiana",
    label: "GF - French Guiana",
    phone: "594",
  },
  { code: "GG", value: "Guernsey", label: "GG - Guernsey", phone: "44" },
  { code: "GH", value: "Ghana", label: "GH - Ghana", phone: "233" },
  { code: "GI", value: "Gibraltar", label: "GI - Gibraltar", phone: "350" },
  { code: "GL", value: "Greenland", label: "GL - Greenland", phone: "299" },
  { code: "GM", value: "Gambia", label: "GM - Gambia", phone: "220" },
  { code: "GN", value: "Guinea", label: "GN - Guinea", phone: "224" },
  { code: "GP", value: "Guadeloupe", label: "GP - Guadeloupe", phone: "590" },
  {
    code: "GQ",
    value: "Equatorial Guinea",
    label: "GQ - Equatorial Guinea",
    phone: "240",
  },
  { code: "GR", value: "Greece", label: "GR - Greece", phone: "30" },
  {
    code: "GS",
    value: "South Georgia and the South Sandwich Islands",
    label: "GS - South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", value: "Guatemala", label: "GT - Guatemala", phone: "502" },
  { code: "GU", value: "Guam", label: "GU - Guam", phone: "1-671" },
  {
    code: "GW",
    value: "Guinea-Bissau",
    label: "GW - Guinea-Bissau",
    phone: "245",
  },
  { code: "GY", value: "Guyana", label: "GY - Guyana", phone: "592" },
  { code: "HK", value: "Hong Kong", label: "HK - Hong Kong", phone: "852" },
  {
    code: "HM",
    value: "Heard Island and McDonald Islands",
    label: "HM - Heard Island and McDonald Islands",
    phone: "672",
  },
  { code: "HN", value: "Honduras", label: "HN - Honduras", phone: "504" },
  { code: "HR", value: "Croatia", label: "HR - Croatia", phone: "385" },
  { code: "HT", value: "Haiti", label: "HT - Haiti", phone: "509" },
  { code: "HU", value: "Hungary", label: "HU - Hungary", phone: "36" },
  { code: "ID", value: "Indonesia", label: "ID - Indonesia", phone: "62" },
  { code: "IE", value: "Ireland", label: "IE - Ireland", phone: "353" },
  { code: "IL", value: "Israel", label: "IL - Israel", phone: "972" },
  { code: "IM", value: "Isle of Man", label: "IM - Isle of Man", phone: "44" },
  { code: "IN", value: "India", label: "IN - India", phone: "91" },
  {
    code: "IO",
    value: "British Indian Ocean Territory",
    label: "IO - British Indian Ocean Territory",
    phone: "246",
  },
  { code: "IQ", value: "Iraq", label: "IQ - Iraq", phone: "964" },
  {
    code: "IR",
    value: "Iran, Islamic Republic of",
    label: "IR - Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "IS", value: "Iceland", label: "IS - Iceland", phone: "354" },
  { code: "IT", value: "Italy", label: "IT - Italy", phone: "39" },
  { code: "JE", value: "Jersey", label: "JE - Jersey", phone: "44" },
  { code: "JM", value: "Jamaica", label: "JM - Jamaica", phone: "1-876" },
  { code: "JO", value: "Jordan", label: "JO - Jordan", phone: "962" },
  { code: "JP", value: "Japan", label: "JP - Japan", phone: "81" },
  { code: "KE", value: "Kenya", label: "KE - Kenya", phone: "254" },
  { code: "KG", value: "Kyrgyzstan", label: "KG - Kyrgyzstan", phone: "996" },
  { code: "KH", value: "Cambodia", label: "KH - Cambodia", phone: "855" },
  { code: "KI", value: "Kiribati", label: "KI - Kiribati", phone: "686" },
  { code: "KM", value: "Comoros", label: "KM - Comoros", phone: "269" },
  {
    code: "KN",
    value: "Saint Kitts and Nevis",
    label: "KN - Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    value: "Korea, Democratic People's Republic of",
    label: "KP - Korea, Democratic People's Republic of",
    phone: "850",
  },
  {
    code: "KR",
    value: "Korea, Republic of",
    label: "KR - Korea, Republic of",
    phone: "82",
  },
  { code: "KW", value: "Kuwait", label: "KW - Kuwait", phone: "965" },
  {
    code: "KY",
    value: "Cayman Islands",
    label: "KY - Cayman Islands",
    phone: "1-345",
  },
  { code: "KZ", value: "Kazakhstan", label: "KZ - Kazakhstan", phone: "7" },
  {
    code: "LA",
    value: "Lao People's Democratic Republic",
    label: "LA - Lao People's Democratic Republic",
    phone: "856",
  },
  { code: "LB", value: "Lebanon", label: "LB - Lebanon", phone: "961" },
  {
    code: "LC",
    value: "Saint Lucia",
    label: "LC - Saint Lucia",
    phone: "1-758",
  },
  {
    code: "LI",
    value: "Liechtenstein",
    label: "LI - Liechtenstein",
    phone: "423",
  },
  { code: "LK", value: "Sri Lanka", label: "LK - Sri Lanka", phone: "94" },
  { code: "LR", value: "Liberia", label: "LR - Liberia", phone: "231" },
  { code: "LS", value: "Lesotho", label: "LS - Lesotho", phone: "266" },
  { code: "LT", value: "Lithuania", label: "LT - Lithuania", phone: "370" },
  { code: "LU", value: "Luxembourg", label: "LU - Luxembourg", phone: "352" },
  { code: "LV", value: "Latvia", label: "LV - Latvia", phone: "371" },
  { code: "LY", value: "Libya", label: "LY - Libya", phone: "218" },
  { code: "MA", value: "Morocco", label: "MA - Morocco", phone: "212" },
  { code: "MC", value: "Monaco", label: "MC - Monaco", phone: "377" },
  {
    code: "MD",
    value: "Moldova, Republic of",
    label: "MD - Moldova, Republic of",
    phone: "373",
  },
  { code: "ME", value: "Montenegro", label: "ME - Montenegro", phone: "382" },
  {
    code: "MF",
    value: "Saint Martin (French part)",
    label: "MF - Saint Martin (French part)",
    phone: "590",
  },
  { code: "MG", value: "Madagascar", label: "MG - Madagascar", phone: "261" },
  {
    code: "MH",
    value: "Marshall Islands",
    label: "MH - Marshall Islands",
    phone: "692",
  },
  {
    code: "MK",
    value: "Macedonia, the Former Yugoslav Republic of",
    label: "MK - Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", value: "Mali", label: "ML - Mali", phone: "223" },
  { code: "MM", value: "Myanmar", label: "MM - Myanmar", phone: "95" },
  { code: "MN", value: "Mongolia", label: "MN - Mongolia", phone: "976" },
  { code: "MO", value: "Macao", label: "MO - Macao", phone: "853" },
  {
    code: "MP",
    value: "Northern Mariana Islands",
    label: "MP - Northern Mariana Islands",
    phone: "1-670",
  },
  { code: "MQ", value: "Martinique", label: "MQ - Martinique", phone: "596" },
  { code: "MR", value: "Mauritania", label: "MR - Mauritania", phone: "222" },
  { code: "MS", value: "Montserrat", label: "MS - Montserrat", phone: "1-664" },
  { code: "MT", value: "Malta", label: "MT - Malta", phone: "356" },
  { code: "MU", value: "Mauritius", label: "MU - Mauritius", phone: "230" },
  { code: "MV", value: "Maldives", label: "MV - Maldives", phone: "960" },
  { code: "MW", value: "Malawi", label: "MW - Malawi", phone: "265" },
  { code: "MX", value: "Mexico", label: "MX - Mexico", phone: "52" },
  { code: "MY", value: "Malaysia", label: "MY - Malaysia", phone: "60" },
  { code: "MZ", value: "Mozambique", label: "MZ - Mozambique", phone: "258" },
  { code: "NA", value: "Namibia", label: "NA - Namibia", phone: "264" },
  {
    code: "NC",
    value: "New Caledonia",
    label: "NC - New Caledonia",
    phone: "687",
  },
  { code: "NE", value: "Niger", label: "NE - Niger", phone: "227" },
  {
    code: "NF",
    value: "Norfolk Island",
    label: "NF - Norfolk Island",
    phone: "672",
  },
  { code: "NG", value: "Nigeria", label: "NG - Nigeria", phone: "234" },
  { code: "NI", value: "Nicaragua", label: "NI - Nicaragua", phone: "505" },
  { code: "NL", value: "Netherlands", label: "NL - Netherlands", phone: "31" },
  { code: "NO", value: "Norway", label: "NO - Norway", phone: "47" },
  { code: "NP", value: "Nepal", label: "NP - Nepal", phone: "977" },
  { code: "NR", value: "Nauru", label: "NR - Nauru", phone: "674" },
  { code: "NU", value: "Niue", label: "NU - Niue", phone: "683" },
  { code: "NZ", value: "New Zealand", label: "NZ - New Zealand", phone: "64" },
  { code: "OM", value: "Oman", label: "OM - Oman", phone: "968" },
  { code: "PA", value: "Panama", label: "PA - Panama", phone: "507" },
  { code: "PE", value: "Peru", label: "PE - Peru", phone: "51" },
  {
    code: "PF",
    value: "French Polynesia",
    label: "PF - French Polynesia",
    phone: "689",
  },
  {
    code: "PG",
    value: "Papua New Guinea",
    label: "PG - Papua New Guinea",
    phone: "675",
  },
  { code: "PH", value: "Philippines", label: "PH - Philippines", phone: "63" },
  { code: "PK", value: "Pakistan", label: "PK - Pakistan", phone: "92" },
  { code: "PL", value: "Poland", label: "PL - Poland", phone: "48" },
  {
    code: "PM",
    value: "Saint Pierre and Miquelon",
    label: "PM - Saint Pierre and Miquelon",
    phone: "508",
  },
  { code: "PN", value: "Pitcairn", label: "PN - Pitcairn", phone: "870" },
  { code: "PR", value: "Puerto Rico", label: "PR - Puerto Rico", phone: "1" },
  {
    code: "PS",
    value: "Palestine, State of",
    label: "PS - Palestine, State of",
    phone: "970",
  },
  { code: "PT", value: "Portugal", label: "PT - Portugal", phone: "351" },
  { code: "PW", value: "Palau", label: "PW - Palau", phone: "680" },
  { code: "PY", value: "Paraguay", label: "PY - Paraguay", phone: "595" },
  { code: "QA", value: "Qatar", label: "QA - Qatar", phone: "974" },
  { code: "RE", value: "Reunion", label: "RE - Reunion", phone: "262" },
  { code: "RO", value: "Romania", label: "RO - Romania", phone: "40" },
  { code: "RS", value: "Serbia", label: "RS - Serbia", phone: "381" },
  {
    code: "RU",
    value: "Russian Federation",
    label: "RU - Russian Federation",
    phone: "7",
  },
  { code: "RW", value: "Rwanda", label: "RW - Rwanda", phone: "250" },
  {
    code: "SA",
    value: "Saudi Arabia",
    label: "SA - Saudi Arabia",
    phone: "966",
  },
  {
    code: "SB",
    value: "Solomon Islands",
    label: "SB - Solomon Islands",
    phone: "677",
  },
  { code: "SC", value: "Seychelles", label: "SC - Seychelles", phone: "248" },
  { code: "SD", value: "Sudan", label: "SD - Sudan", phone: "249" },
  { code: "SE", value: "Sweden", label: "SE - Sweden", phone: "46" },
  { code: "SG", value: "Singapore", label: "SG - Singapore", phone: "65" },
  {
    code: "SH",
    value: "Saint Helena",
    label: "SH - Saint Helena",
    phone: "290",
  },
  { code: "SI", value: "Slovenia", label: "SI - Slovenia", phone: "386" },
  {
    code: "SJ",
    value: "Svalbard and Jan Mayen",
    label: "SJ - Svalbard and Jan Mayen",
    phone: "47",
  },
  { code: "SK", value: "Slovakia", label: "SK - Slovakia", phone: "421" },
  {
    code: "SL",
    value: "Sierra Leone",
    label: "SL - Sierra Leone",
    phone: "232",
  },
  { code: "SM", value: "San Marino", label: "SM - San Marino", phone: "378" },
  { code: "SN", value: "Senegal", label: "SN - Senegal", phone: "221" },
  { code: "SO", value: "Somalia", label: "SO - Somalia", phone: "252" },
  { code: "SR", value: "Suriname", label: "SR - Suriname", phone: "597" },
  { code: "SS", value: "South Sudan", label: "SS - South Sudan", phone: "211" },
  {
    code: "ST",
    value: "Sao Tome and Principe",
    label: "ST - Sao Tome and Principe",
    phone: "239",
  },
  { code: "SV", value: "El Salvador", label: "SV - El Salvador", phone: "503" },
  {
    code: "SX",
    value: "Sint Maarten (Dutch part)",
    label: "SX - Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    value: "Syrian Arab Republic",
    label: "SY - Syrian Arab Republic",
    phone: "963",
  },
  { code: "SZ", value: "Swaziland", label: "SZ - Swaziland", phone: "268" },
  {
    code: "TC",
    value: "Turks and Caicos Islands",
    label: "TC - Turks and Caicos Islands",
    phone: "1-649",
  },
  { code: "TD", value: "Chad", label: "TD - Chad", phone: "235" },
  {
    code: "TF",
    value: "French Southern Territories",
    label: "TF - French Southern Territories",
    phone: "262",
  },
  { code: "TG", value: "Togo", label: "TG - Togo", phone: "228" },
  { code: "TH", value: "Thailand", label: "TH - Thailand", phone: "66" },
  { code: "TJ", value: "Tajikistan", label: "TJ - Tajikistan", phone: "992" },
  { code: "TK", value: "Tokelau", label: "TK - Tokelau", phone: "690" },
  { code: "TL", value: "Timor-Leste", label: "TL - Timor-Leste", phone: "670" },
  {
    code: "TM",
    value: "Turkmenistan",
    label: "TM - Turkmenistan",
    phone: "993",
  },
  { code: "TN", value: "Tunisia", label: "TN - Tunisia", phone: "216" },
  { code: "TO", value: "Tonga", label: "TO - Tonga", phone: "676" },
  { code: "TR", value: "Turkey", label: "TR - Turkey", phone: "90" },
  {
    code: "TT",
    value: "Trinidad and Tobago",
    label: "TT - Trinidad and Tobago",
    phone: "1-868",
  },
  { code: "TV", value: "Tuvalu", label: "TV - Tuvalu", phone: "688" },
  {
    code: "TW",
    value: "Taiwan, Province of China",
    label: "TW - Taiwan, Province of China",
    phone: "886",
  },
  {
    code: "TZ",
    value: "United Republic of Tanzania",
    label: "TZ - United Republic of Tanzania",
    phone: "255",
  },
  { code: "UA", value: "Ukraine", label: "UA - Ukraine", phone: "380" },
  { code: "UG", value: "Uganda", label: "UG - Uganda", phone: "256" },
  {
    code: "US",
    value: "United States",
    label: "US - United States",
    phone: "1",
  },
  { code: "UY", value: "Uruguay", label: "UY - Uruguay", phone: "598" },
  { code: "UZ", value: "Uzbekistan", label: "UZ - Uzbekistan", phone: "998" },
  {
    code: "VA",
    value: "Holy See (Vatican City State)",
    label: "VA - Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    value: "Saint Vincent and the Grenadines",
    label: "VC - Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  { code: "VE", value: "Venezuela", label: "VE - Venezuela", phone: "58" },
  {
    code: "VG",
    value: "British Virgin Islands",
    label: "VG - British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    value: "US Virgin Islands",
    label: "VI - US Virgin Islands",
    phone: "1-340",
  },
  { code: "VN", value: "Vietnam", label: "VN - Vietnam", phone: "84" },
  { code: "VU", value: "Vanuatu", label: "VU - Vanuatu", phone: "678" },
  {
    code: "WF",
    value: "Wallis and Futuna",
    label: "WF - Wallis and Futuna",
    phone: "681",
  },
  { code: "WS", value: "Samoa", label: "WS - Samoa", phone: "685" },
  { code: "XK", value: "Kosovo", label: "XK - Kosovo", phone: "383" },
  { code: "YE", value: "Yemen", label: "YE - Yemen", phone: "967" },
  { code: "YT", value: "Mayotte", label: "YT - Mayotte", phone: "262" },
  {
    code: "ZA",
    value: "South Africa",
    label: "ZA - South Africa",
    phone: "27",
  },
  { code: "ZM", value: "Zambia", label: "ZM - Zambia", phone: "260" },
  { code: "ZW", value: "Zimbabwe", label: "ZW - Zimbabwe", phone: "263" },
];
