export const countries = [
  { code: "AD", value: "Andorra", label: "Andorra", phone: "376" },
  {
    code: "AE",
    value: "United Arab Emirates",
    label: "United Arab Emirates",
    phone: "971",
  },
  { code: "AF", value: "Afghanistan", label: "Afghanistan", phone: "93" },
  {
    code: "AG",
    value: "Antigua and Barbuda",
    label: "Antigua and Barbuda",
    phone: "1-268",
  },
  { code: "AI", value: "Anguilla", label: "Anguilla", phone: "1-264" },
  { code: "AL", value: "Albania", label: "Albania", phone: "355" },
  { code: "AM", value: "Armenia", label: "Armenia", phone: "374" },
  { code: "AO", value: "Angola", label: "Angola", phone: "244" },
  { code: "AQ", value: "Antarctica", label: "Antarctica", phone: "672" },
  { code: "AR", value: "Argentina", label: "Argentina", phone: "54" },
  {
    code: "AS",
    value: "American Samoa",
    label: "American Samoa",
    phone: "1-684",
  },
  { code: "AT", value: "Austria", label: "Austria", phone: "43" },
  { code: "AU", value: "Australia", label: "Australia", phone: "61" },
  { code: "AW", value: "Aruba", label: "Aruba", phone: "297" },
  {
    code: "AX",
    value: "Alland Islands",
    label: "Alland Islands",
    phone: "358",
  },
  { code: "AZ", value: "Azerbaijan", label: "Azerbaijan", phone: "994" },
  {
    code: "BA",
    value: "Bosnia and Herzegovina",
    label: "Bosnia and Herzegovina",
    phone: "387",
  },
  { code: "BB", value: "Barbados", label: "Barbados", phone: "1-246" },
  { code: "BD", value: "Bangladesh", label: "Bangladesh", phone: "880" },
  { code: "BE", value: "Belgium", label: "Belgium", phone: "32" },
  { code: "BF", value: "Burkina Faso", label: "Burkina Faso", phone: "226" },
  { code: "BG", value: "Bulgaria", label: "Bulgaria", phone: "359" },
  { code: "BH", value: "Bahrain", label: "Bahrain", phone: "973" },
  { code: "BI", value: "Burundi", label: "Burundi", phone: "257" },
  { code: "BJ", value: "Benin", label: "Benin", phone: "229" },
  {
    code: "BL",
    value: "Saint Barthelemy",
    label: "Saint Barthelemy",
    phone: "590",
  },
  { code: "BM", value: "Bermuda", label: "Bermuda", phone: "1-441" },
  {
    code: "BN",
    value: "Brunei Darussalam",
    label: "Brunei Darussalam",
    phone: "673",
  },
  { code: "BO", value: "Bolivia", label: "Bolivia", phone: "591" },
  { code: "BR", value: "Brazil", label: "Brazil", phone: "55" },
  { code: "BS", value: "Bahamas", label: "Bahamas", phone: "1-242" },
  { code: "BT", value: "Bhutan", label: "Bhutan", phone: "975" },
  { code: "BV", value: "Bouvet Island", label: "Bouvet Island", phone: "47" },
  { code: "BW", value: "Botswana", label: "Botswana", phone: "267" },
  { code: "BY", value: "Belarus", label: "Belarus", phone: "375" },
  { code: "BZ", value: "Belize", label: "Belize", phone: "501" },
  { code: "CA", value: "Canada", label: "Canada", phone: "1" },
  {
    code: "CC",
    value: "Cocos (Keeling) Islands",
    label: "Cocos (Keeling) Islands",
    phone: "61",
  },
  {
    code: "CD",
    value: "Congo, Republic of the",
    label: "Congo, Republic of the",
    phone: "242",
  },
  {
    code: "CF",
    value: "Central African Republic",
    label: "Central African Republic",
    phone: "236",
  },
  {
    code: "CG",
    value: "Congo, Democratic Republic of the",
    label: "Congo, Democratic Republic of the",
    phone: "243",
  },
  { code: "CH", value: "Switzerland", label: "Switzerland", phone: "41" },
  {
    code: "CI",
    value: "Cote d'Ivoire",
    label: "Cote d'Ivoire",
    phone: "225",
  },
  { code: "CK", value: "Cook Islands", label: "Cook Islands", phone: "682" },
  { code: "CL", value: "Chile", label: "Chile", phone: "56" },
  { code: "CM", value: "Cameroon", label: "Cameroon", phone: "237" },
  { code: "CN", value: "China", label: "China", phone: "86" },
  { code: "CO", value: "Colombia", label: "Colombia", phone: "57" },
  { code: "CR", value: "Costa Rica", label: "Costa Rica", phone: "506" },
  { code: "CU", value: "Cuba", label: "Cuba", phone: "53" },
  { code: "CV", value: "Cape Verde", label: "Cape Verde", phone: "238" },
  { code: "CW", value: "Curacao", label: "Curacao", phone: "599" },
  {
    code: "CX",
    value: "Christmas Island",
    label: "Christmas Island",
    phone: "61",
  },
  { code: "CY", value: "Cyprus", label: "Cyprus", phone: "357" },
  {
    code: "CZ",
    value: "Czech Republic",
    label: "Czech Republic",
    phone: "420",
  },
  { code: "DE", value: "Germany", label: "Germany", phone: "49" },
  { code: "DJ", value: "Djibouti", label: "Djibouti", phone: "253" },
  { code: "DK", value: "Denmark", label: "Denmark", phone: "45" },
  { code: "DM", value: "Dominica", label: "Dominica", phone: "1-767" },
  {
    code: "DO",
    value: "Dominican Republic",
    label: "Dominican Republic",
    phone: "1-809",
  },
  { code: "DZ", value: "Algeria", label: "Algeria", phone: "213" },
  { code: "EC", value: "Ecuador", label: "Ecuador", phone: "593" },
  { code: "EE", value: "Estonia", label: "Estonia", phone: "372" },
  { code: "EG", value: "Egypt", label: "Egypt", phone: "20" },
  {
    code: "EH",
    value: "Western Sahara",
    label: "Western Sahara",
    phone: "212",
  },
  { code: "ER", value: "Eritrea", label: "Eritrea", phone: "291" },
  { code: "ES", value: "Spain", label: "Spain", phone: "34" },
  { code: "ET", value: "Ethiopia", label: "Ethiopia", phone: "251" },
  { code: "FI", value: "Finland", label: "Finland", phone: "358" },
  { code: "FJ", value: "Fiji", label: "Fiji", phone: "679" },
  {
    code: "FK",
    value: "Falkland Islands (Malvinas)",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
  },
  {
    code: "FM",
    value: "Micronesia, Federated States of",
    label: "Micronesia, Federated States of",
    phone: "691",
  },
  {
    code: "FO",
    value: "Faroe Islands",
    label: "Faroe Islands",
    phone: "298",
  },
  { code: "FR", value: "France", label: "France", phone: "33" },
  { code: "GA", value: "Gabon", label: "Gabon", phone: "241" },
  {
    code: "GB",
    value: "United Kingdom",
    label: "United Kingdom",
    phone: "44",
  },
  { code: "GD", value: "Grenada", label: "Grenada", phone: "1-473" },
  { code: "GE", value: "Georgia", label: "Georgia", phone: "995" },
  {
    code: "GF",
    value: "French Guiana",
    label: "French Guiana",
    phone: "594",
  },
  { code: "GG", value: "Guernsey", label: "Guernsey", phone: "44" },
  { code: "GH", value: "Ghana", label: "Ghana", phone: "233" },
  { code: "GI", value: "Gibraltar", label: "Gibraltar", phone: "350" },
  { code: "GL", value: "Greenland", label: "Greenland", phone: "299" },
  { code: "GM", value: "Gambia", label: "Gambia", phone: "220" },
  { code: "GN", value: "Guinea", label: "Guinea", phone: "224" },
  { code: "GP", value: "Guadeloupe", label: "Guadeloupe", phone: "590" },
  {
    code: "GQ",
    value: "Equatorial Guinea",
    label: "Equatorial Guinea",
    phone: "240",
  },
  { code: "GR", value: "Greece", label: "Greece", phone: "30" },
  {
    code: "GS",
    value: "South Georgia and the South Sandwich Islands",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
  },
  { code: "GT", value: "Guatemala", label: "Guatemala", phone: "502" },
  { code: "GU", value: "Guam", label: "Guam", phone: "1-671" },
  {
    code: "GW",
    value: "Guinea-Bissau",
    label: "Guinea-Bissau",
    phone: "245",
  },
  { code: "GY", value: "Guyana", label: "Guyana", phone: "592" },
  { code: "HK", value: "Hong Kong", label: "Hong Kong", phone: "852" },
  {
    code: "HM",
    value: "Heard Island and McDonald Islands",
    label: "Heard Island and McDonald Islands",
    phone: "672",
  },
  { code: "HN", value: "Honduras", label: "Honduras", phone: "504" },
  { code: "HR", value: "Croatia", label: "Croatia", phone: "385" },
  { code: "HT", value: "Haiti", label: "Haiti", phone: "509" },
  { code: "HU", value: "Hungary", label: "Hungary", phone: "36" },
  { code: "ID", value: "Indonesia", label: "Indonesia", phone: "62" },
  { code: "IE", value: "Ireland", label: "Ireland", phone: "353" },
  { code: "IL", value: "Israel", label: "Israel", phone: "972" },
  { code: "IM", value: "Isle of Man", label: "Isle of Man", phone: "44" },
  { code: "IN", value: "India", label: "India", phone: "91" },
  {
    code: "IO",
    value: "British Indian Ocean Territory",
    label: "British Indian Ocean Territory",
    phone: "246",
  },
  { code: "IQ", value: "Iraq", label: "Iraq", phone: "964" },
  {
    code: "IR",
    value: "Iran, Islamic Republic of",
    label: "Iran, Islamic Republic of",
    phone: "98",
  },
  { code: "IS", value: "Iceland", label: "Iceland", phone: "354" },
  { code: "IT", value: "Italy", label: "Italy", phone: "39" },
  { code: "JE", value: "Jersey", label: "Jersey", phone: "44" },
  { code: "JM", value: "Jamaica", label: "Jamaica", phone: "1-876" },
  { code: "JO", value: "Jordan", label: "Jordan", phone: "962" },
  { code: "JP", value: "Japan", label: "Japan", phone: "81" },
  { code: "KE", value: "Kenya", label: "Kenya", phone: "254" },
  { code: "KG", value: "Kyrgyzstan", label: "Kyrgyzstan", phone: "996" },
  { code: "KH", value: "Cambodia", label: "Cambodia", phone: "855" },
  { code: "KI", value: "Kiribati", label: "Kiribati", phone: "686" },
  { code: "KM", value: "Comoros", label: "Comoros", phone: "269" },
  {
    code: "KN",
    value: "Saint Kitts and Nevis",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
  },
  {
    code: "KP",
    value: "Korea, Democratic People's Republic of",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
  },
  {
    code: "KR",
    value: "Korea, Republic of",
    label: "Korea, Republic of",
    phone: "82",
  },
  { code: "KW", value: "Kuwait", label: "Kuwait", phone: "965" },
  {
    code: "KY",
    value: "Cayman Islands",
    label: "Cayman Islands",
    phone: "1-345",
  },
  { code: "KZ", value: "Kazakhstan", label: "Kazakhstan", phone: "7" },
  {
    code: "LA",
    value: "Lao People's Democratic Republic",
    label: "Lao People's Democratic Republic",
    phone: "856",
  },
  { code: "LB", value: "Lebanon", label: "Lebanon", phone: "961" },
  { code: "LC", value: "Saint Lucia", label: "Saint Lucia", phone: "1-758" },
  {
    code: "LI",
    value: "Liechtenstein",
    label: "Liechtenstein",
    phone: "423",
  },
  { code: "LK", value: "Sri Lanka", label: "Sri Lanka", phone: "94" },
  { code: "LR", value: "Liberia", label: "Liberia", phone: "231" },
  { code: "LS", value: "Lesotho", label: "Lesotho", phone: "266" },
  { code: "LT", value: "Lithuania", label: "Lithuania", phone: "370" },
  { code: "LU", value: "Luxembourg", label: "Luxembourg", phone: "352" },
  { code: "LV", value: "Latvia", label: "Latvia", phone: "371" },
  { code: "LY", value: "Libya", label: "Libya", phone: "218" },
  { code: "MA", value: "Morocco", label: "Morocco", phone: "212" },
  { code: "MC", value: "Monaco", label: "Monaco", phone: "377" },
  {
    code: "MD",
    value: "Moldova, Republic of",
    label: "Moldova, Republic of",
    phone: "373",
  },
  { code: "ME", value: "Montenegro", label: "Montenegro", phone: "382" },
  {
    code: "MF",
    value: "Saint Martin (French part)",
    label: "Saint Martin (French part)",
    phone: "590",
  },
  { code: "MG", value: "Madagascar", label: "Madagascar", phone: "261" },
  {
    code: "MH",
    value: "Marshall Islands",
    label: "Marshall Islands",
    phone: "692",
  },
  {
    code: "MK",
    value: "Macedonia, the Former Yugoslav Republic of",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
  },
  { code: "ML", value: "Mali", label: "Mali", phone: "223" },
  { code: "MM", value: "Myanmar", label: "Myanmar", phone: "95" },
  { code: "MN", value: "Mongolia", label: "Mongolia", phone: "976" },
  { code: "MO", value: "Macao", label: "Macao", phone: "853" },
  {
    code: "MP",
    value: "Northern Mariana Islands",
    label: "Northern Mariana Islands",
    phone: "1-670",
  },
  { code: "MQ", value: "Martinique", label: "Martinique", phone: "596" },
  { code: "MR", value: "Mauritania", label: "Mauritania", phone: "222" },
  { code: "MS", value: "Montserrat", label: "Montserrat", phone: "1-664" },
  { code: "MT", value: "Malta", label: "Malta", phone: "356" },
  { code: "MU", value: "Mauritius", label: "Mauritius", phone: "230" },
  { code: "MV", value: "Maldives", label: "Maldives", phone: "960" },
  { code: "MW", value: "Malawi", label: "Malawi", phone: "265" },
  { code: "MX", value: "Mexico", label: "Mexico", phone: "52" },
  { code: "MY", value: "Malaysia", label: "Malaysia", phone: "60" },
  { code: "MZ", value: "Mozambique", label: "Mozambique", phone: "258" },
  { code: "NA", value: "Namibia", label: "Namibia", phone: "264" },
  {
    code: "NC",
    value: "New Caledonia",
    label: "New Caledonia",
    phone: "687",
  },
  { code: "NE", value: "Niger", label: "Niger", phone: "227" },
  {
    code: "NF",
    value: "Norfolk Island",
    label: "Norfolk Island",
    phone: "672",
  },
  { code: "NG", value: "Nigeria", label: "Nigeria", phone: "234" },
  { code: "NI", value: "Nicaragua", label: "Nicaragua", phone: "505" },
  { code: "NL", value: "Netherlands", label: "Netherlands", phone: "31" },
  { code: "NO", value: "Norway", label: "Norway", phone: "47" },
  { code: "NP", value: "Nepal", label: "Nepal", phone: "977" },
  { code: "NR", value: "Nauru", label: "Nauru", phone: "674" },
  { code: "NU", value: "Niue", label: "Niue", phone: "683" },
  { code: "NZ", value: "New Zealand", label: "New Zealand", phone: "64" },
  { code: "OM", value: "Oman", label: "Oman", phone: "968" },
  { code: "PA", value: "Panama", label: "Panama", phone: "507" },
  { code: "PE", value: "Peru", label: "Peru", phone: "51" },
  {
    code: "PF",
    value: "French Polynesia",
    label: "French Polynesia",
    phone: "689",
  },
  {
    code: "PG",
    value: "Papua New Guinea",
    label: "Papua New Guinea",
    phone: "675",
  },
  { code: "PH", value: "Philippines", label: "Philippines", phone: "63" },
  { code: "PK", value: "Pakistan", label: "Pakistan", phone: "92" },
  { code: "PL", value: "Poland", label: "Poland", phone: "48" },
  {
    code: "PM",
    value: "Saint Pierre and Miquelon",
    label: "Saint Pierre and Miquelon",
    phone: "508",
  },
  { code: "PN", value: "Pitcairn", label: "Pitcairn", phone: "870" },
  { code: "PR", value: "Puerto Rico", label: "Puerto Rico", phone: "1" },
  {
    code: "PS",
    value: "Palestine, State of",
    label: "Palestine, State of",
    phone: "970",
  },
  { code: "PT", value: "Portugal", label: "Portugal", phone: "351" },
  { code: "PW", value: "Palau", label: "Palau", phone: "680" },
  { code: "PY", value: "Paraguay", label: "Paraguay", phone: "595" },
  { code: "QA", value: "Qatar", label: "Qatar", phone: "974" },
  { code: "RE", value: "Reunion", label: "Reunion", phone: "262" },
  { code: "RO", value: "Romania", label: "Romania", phone: "40" },
  { code: "RS", value: "Serbia", label: "Serbia", phone: "381" },
  {
    code: "RU",
    value: "Russian Federation",
    label: "Russian Federation",
    phone: "7",
  },
  { code: "RW", value: "Rwanda", label: "Rwanda", phone: "250" },
  { code: "SA", value: "Saudi Arabia", label: "Saudi Arabia", phone: "966" },
  {
    code: "SB",
    value: "Solomon Islands",
    label: "Solomon Islands",
    phone: "677",
  },
  { code: "SC", value: "Seychelles", label: "Seychelles", phone: "248" },
  { code: "SD", value: "Sudan", label: "Sudan", phone: "249" },
  { code: "SE", value: "Sweden", label: "Sweden", phone: "46" },
  { code: "SG", value: "Singapore", label: "Singapore", phone: "65" },
  { code: "SH", value: "Saint Helena", label: "Saint Helena", phone: "290" },
  { code: "SI", value: "Slovenia", label: "Slovenia", phone: "386" },
  {
    code: "SJ",
    value: "Svalbard and Jan Mayen",
    label: "Svalbard and Jan Mayen",
    phone: "47",
  },
  { code: "SK", value: "Slovakia", label: "Slovakia", phone: "421" },
  { code: "SL", value: "Sierra Leone", label: "Sierra Leone", phone: "232" },
  { code: "SM", value: "San Marino", label: "San Marino", phone: "378" },
  { code: "SN", value: "Senegal", label: "Senegal", phone: "221" },
  { code: "SO", value: "Somalia", label: "Somalia", phone: "252" },
  { code: "SR", value: "Suriname", label: "Suriname", phone: "597" },
  { code: "SS", value: "South Sudan", label: "South Sudan", phone: "211" },
  {
    code: "ST",
    value: "Sao Tome and Principe",
    label: "Sao Tome and Principe",
    phone: "239",
  },
  { code: "SV", value: "El Salvador", label: "El Salvador", phone: "503" },
  {
    code: "SX",
    value: "Sint Maarten (Dutch part)",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
  },
  {
    code: "SY",
    value: "Syrian Arab Republic",
    label: "Syrian Arab Republic",
    phone: "963",
  },
  { code: "SZ", value: "Swaziland", label: "Swaziland", phone: "268" },
  {
    code: "TC",
    value: "Turks and Caicos Islands",
    label: "Turks and Caicos Islands",
    phone: "1-649",
  },
  { code: "TD", value: "Chad", label: "Chad", phone: "235" },
  {
    code: "TF",
    value: "French Southern Territories",
    label: "French Southern Territories",
    phone: "262",
  },
  { code: "TG", value: "Togo", label: "Togo", phone: "228" },
  { code: "TH", value: "Thailand", label: "Thailand", phone: "66" },
  { code: "TJ", value: "Tajikistan", label: "Tajikistan", phone: "992" },
  { code: "TK", value: "Tokelau", label: "Tokelau", phone: "690" },
  { code: "TL", value: "Timor-Leste", label: "Timor-Leste", phone: "670" },
  { code: "TM", value: "Turkmenistan", label: "Turkmenistan", phone: "993" },
  { code: "TN", value: "Tunisia", label: "Tunisia", phone: "216" },
  { code: "TO", value: "Tonga", label: "Tonga", phone: "676" },
  { code: "TR", value: "Turkey", label: "Turkey", phone: "90" },
  {
    code: "TT",
    value: "Trinidad and Tobago",
    label: "Trinidad and Tobago",
    phone: "1-868",
  },
  { code: "TV", value: "Tuvalu", label: "Tuvalu", phone: "688" },
  {
    code: "TW",
    value: "Taiwan, Province of China",
    label: "Taiwan, Province of China",
    phone: "886",
  },
  {
    code: "TZ",
    value: "United Republic of Tanzania",
    label: "United Republic of Tanzania",
    phone: "255",
  },
  { code: "UA", value: "Ukraine", label: "Ukraine", phone: "380" },
  { code: "UG", value: "Uganda", label: "Uganda", phone: "256" },
  { code: "US", value: "United States", label: "United States", phone: "1" },
  { code: "UY", value: "Uruguay", label: "Uruguay", phone: "598" },
  { code: "UZ", value: "Uzbekistan", label: "Uzbekistan", phone: "998" },
  {
    code: "VA",
    value: "Holy See (Vatican City State)",
    label: "Holy See (Vatican City State)",
    phone: "379",
  },
  {
    code: "VC",
    value: "Saint Vincent and the Grenadines",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
  },
  { code: "VE", value: "Venezuela", label: "Venezuela", phone: "58" },
  {
    code: "VG",
    value: "British Virgin Islands",
    label: "British Virgin Islands",
    phone: "1-284",
  },
  {
    code: "VI",
    value: "US Virgin Islands",
    label: "US Virgin Islands",
    phone: "1-340",
  },
  { code: "VN", value: "Vietnam", label: "Vietnam", phone: "84" },
  { code: "VU", value: "Vanuatu", label: "Vanuatu", phone: "678" },
  {
    code: "WF",
    value: "Wallis and Futuna",
    label: "Wallis and Futuna",
    phone: "681",
  },
  { code: "WS", value: "Samoa", label: "Samoa", phone: "685" },
  { code: "XK", value: "Kosovo", label: "Kosovo", phone: "383" },
  { code: "YE", value: "Yemen", label: "Yemen", phone: "967" },
  { code: "YT", value: "Mayotte", label: "Mayotte", phone: "262" },
  { code: "ZA", value: "South Africa", label: "South Africa", phone: "27" },
  { code: "ZM", value: "Zambia", label: "Zambia", phone: "260" },
  { code: "ZW", value: "Zimbabwe", label: "Zimbabwe", phone: "263" },
];
